inherit_gem:
  rubocop-rails_config:
    - config/rails.yml

Style/FrozenStringLiteralComment:
  Enabled: false  # https://qiita.com/universato/items/1dd8943df07f2445655e

Layout/LeadingCommentSpace:
  Enabled: false  # 一時的に無効にするときに使っている

Layout/CommentIndentation:
  Enabled: false  # 一時的に無効にするときにインデントはズレる
